### ISSUE TITLE
Add configuration for filtering specific parameters out of logs

### ISSUE THREAD

**Issue by seddy** [reevoo/sapience-rb#4]
Raised out of this PR: https://github.com/reevoo/logstasher/pull/7

I propose to make exactly the same change here, so functionally we'll still see when parameters have been passed, but not show the contents of those parameters in logs.  Unless anyone has any better alternatives, I'll use `[FILTERED]` to keep in line with general Rails logging (http://guides.rubyonrails.org/security.html#logging).  

The default configuration should filter out `password` and `password_confirmation`.

**Comment by mhenrixon** [comment]
Agree! We can then consider how to proceed with the configuration as the application is booted. We have some work to do there so don't worry too much about this for the PR. Sloppy paste of the Logstasher implementation in some form should do the trick.

**Comment by ionut998** [comment]
Am I right of thinking that this is already fixed?
I can see that the actual password has been filtered in the logs
```
::1 - - [29/Sep/2016:12:59:23 -0700] "POST /api/v1/session HTTP/1.1" 500 186945 15.0711
{"@timestamp":"2016-09-29 19:59:40 UTC","@version":"1","severity":"info","path":"/api/v1/session","params":{"email":"example@reevoo.com","password":"[FILTERED]"}, "method":"POST","total":68.09,"db":0.0,"status":201,"request_path":"/api/v1/session","tags":["myreevoo_admin_api"]}
```

**Comment by ionut998** [comment]
Not actually, I was looking at the wrong logs 😄
Here are the sapience logs:
```2016-09-29 13:24:28.864263 [36mI[0m [12069:70194553191400 base.rb:26] [36mClientPortal::API[0m -- { :method[0;37m => [0m[0;33m"POST"[0m, :request_path[0;37m => [0m[0;33m"/api/v1/session"[0m, :format[0;37m => [0m[0;36m:json[0m, :status[0;37m => [0m[1;34m201[0m, :class_name[0;37m => [0m[0;33m"ClientPortal::API::UserAuthentication"[0m, :action[0;37m => [0m[0;33m"index"[0m, :host[0;37m => [0m[0;33m"localhost"[0m, :ip[0;37m => [0m[0;33m"::1"[0m, :ua[0;37m => [0m[0;33m"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"[0m, :tags[0;37m => [0m[], :params[0;37m => [0m{ "email"[0;37m => [0m[0;33m"example@reevoo.com"[0m, "password"[0;37m => [0m[0;33m"**password**"[0m }, :runtimes[0;37m => [0m{ :total[0;37m => [0m[1;34m26.712[0m, :view[0;37m => [0m[1;34m26.712[0m, :db[0;37m => [0m[1;34m0.0[0m } }```
